export class CurrencyData {
    value: string;
    innertext: string;
}

export const CURRENCY_SPEND_CALCULATIONS:string = "Spend Calculation";

export const CurrencyVal: CurrencyData[] = [

        {"value": "America (United States) Dollars - USD", "innertext": "America (United States) Dollars - USD"},
		{"value": "Afghanistan Afghanis - AFN", "innertext": "Afghanistan Afghanis - AFN"},
		{"value": "Albania Leke - ALL", "innertext": "Albania Leke - ALL"},
		{"value": "Algeria Dinars - DZD", "innertext": "Algeria Dinars - DZD"},
		{"value": "Argentina Pesos - ARS", "innertext": "Argentina Pesos - ARS"},
		{"value": "Australia Dollars - AUD", "innertext": "Australia Dollars - AUD"},
		{"value": "Austria Schillings - ATS", "innertext": "Austria Schillings - ATS"},

		{"value": "Bahamas Dollars - BSD", "innertext": "Bahamas Dollars - BSD"},
		{"value": "Bahrain Dinars - BHD", "innertext": "Bahrain Dinars - BHD"},
		{"value": "Bangladesh Taka - BDT", "innertext": "Bangladesh Taka - BDT"},
		{"value": "Barbados Dollars - BBD", "innertext": "Barbados Dollars - BBD"},
		{"value": "Belgium Francs - BEF", "innertext": "Belgium Francs - BEF"},
		{"value": "Bermuda Dollars - BMD", "innertext": "Bermuda Dollars - BMD"},
		{"value": "Brazil Reais - BRL", "innertext": "Brazil Reais - BRL"},
		{"value": "Bulgaria Leva - BGN", "innertext": "Bulgaria Leva - BGN"},

		{"value": "Canada Dollars - CAD", "innertext": "Canada Dollars - CAD"},
		{"value": "CFA BCEAO Francs - XOF", "innertext": "CFA BCEAO Francs - XOF"},
		{"value": "CFA BEAC Francs - XAF", "innertext": "CFA BEAC Francs - XAF"},
		{"value": "Chile Pesos - CLP", "innertext": "Chile Pesos - CLP"},
		{"value": "China Yuan Renminbi - CNY", "innertext": "China Yuan Renminbi - CNY"},
		{"value": "RMB (China Yuan Renminbi) - CNY", "innertext": "RMB (China Yuan Renminbi) - CNY"},
		{"value": "Colombia Pesos - COP", "innertext": "Colombia Pesos - COP"},
		{"value": "CFP Francs - XPF", "innertext": "CFP Francs - XPF"},
		{"value": "Costa Rica Colones - CRC", "innertext": "Costa Rica Colones - CRC"},
		{"value": "Croatia Kuna - HRK", "innertext": "Croatia Kuna - HRK"},
		{"value": "Cyprus Pounds - CYP", "innertext": "Cyprus Pounds - CYP"},
		{"value": "Czech Republic Koruny - CZK", "innertext": "Czech Republic Koruny - CZK"},

		{"value": "Denmark Kroner - DKK", "innertext": "Denmark Kroner - DKK"},
		{"value": "Deutsche (Germany) Marks - DEM", "innertext": "Deutsche (Germany) Marks - DEM"},
		{"value": "Dominican Republic Pesos - DOP", "innertext": "Dominican Republic Pesos - DOP"},
		{"value": "Dutch (Netherlands) Guilders - NLG", "innertext": "Dutch (Netherlands) Guilders - NLG"},

		{"value": "Eastern Caribbean Dollars - XCD", "innertext": "Eastern Caribbean Dollars - XCD"},
		{"value": "Egypt Pounds - EGP", "innertext": "Egypt Pounds - EGP"},
		{"value": "Estonia Krooni - EEK", "innertext": "Estonia Krooni - EEK"},
		{"value": "Euro - EUR", "innertext": "Euro - EUR"},
		{"value": "Fiji Dollars - FJD", "innertext": "Fiji Dollars - FJD"},
		{"value": "Finland Markkaa - FIM", "innertext": "Finland Markkaa - FIM"},
		{"value": "France Francs - FRF*", "innertext": "France Francs - FRF*"},
		{"value": "Germany Deutsche Marks - DEM", "innertext": "Germany Deutsche Marks - DEM"},
		{"value": "Gold Ounces - XAU", "innertext": "Gold Ounces - XAU"},
		{"value": "Greece Drachmae - GRD", "innertext": "Greece Drachmae - GRD"},
		{"value": "Guatemalan Quetzal - GTQ", "innertext": "Guatemalan Quetzal - GTQ"},
		{"value": "Holland (Netherlands) Guilders - NLG", "innertext": "Holland (Netherlands) Guilders - NLG"},
		{"value": "Hong Kong Dollars - HKD", "innertext": "Hong Kong Dollars - HKD"},
		{"value": "Hungary Forint - HUF", "innertext": "Hungary Forint - HUF"},

		{"value": "Iceland Kronur - ISK", "innertext": "Iceland Kronur - ISK"},
		{"value": "IMF Special Drawing Right - XDR", "innertext": "IMF Special Drawing Right - XDR"},
		{"value": "Indian Rupees - INR", "innertext": "Indian Rupees - INR"},
		{"value": "Indonesia Rupiahs - IDR", "innertext": "Indonesia Rupiahs - IDR"},
		{"value": "Iran Rials - IRR", "innertext": "Iran Rials - IRR"},
		{"value": "Iraq Dinars - IQD", "innertext": "Iraq Dinars - IQD"},
		{"value": "Ireland Pounds - IEP*", "innertext": "Ireland Pounds - IEP*"},
		{"value": "Israel New Shekels - ILS", "innertext": "Israel New Shekels - ILS"},
		{"value": "Italy Lire - ITL*", "innertext": "Italy Lire - ITL*"},

		{"value": "Jamaica Dollars - JMD", "innertext": "Jamaica Dollars - JMD"},
		{"value": "Japan Yen - JPY", "innertext": "Japan Yen - JPY"},
		{"value": "Jordan Dinars - JOD", "innertext": "Jordan Dinars - JOD"},
		{"value": "Kenya Shillings - KES", "innertext": "Kenya Shillings - KES"},
		{"value": "Korea (South) Won - KRW", "innertext": "Korea (South) Won - KRW"},
		{"value": "Kuwait Dinars - KWD", "innertext": "Kuwait Dinars - KWD"},
		{"value": "Lebanon Pounds - LBP", "innertext": "Lebanon Pounds - LBP"},
		{"value": "Luxembourg Francs - LUF", "innertext": "Luxembourg Francs - LUF"},

		{"value": "Malaysia Ringgits - MYR", "innertext": "Malaysia Ringgits - MYR"},
		{"value": "Malta Liri - MTL", "innertext": "Malta Liri – MTL"},
		{"value": "Mauritius Rupees - MUR", "innertext": "Mauritius Rupees – MUR"},
		{"value": "Mexico Pesos - MXN", "innertext": "Mexico Pesos – MXN"},
		{"value": "Morocco Dirhams - MAD", "innertext": "Morocco Dirhams – MAD"},
		{"value": "Netherlands Guilders - NLG", "innertext": "Netherlands Guilders – NLG"},
		{"value": "New Zealand Dollars - NZD", "innertext": "New Zealand Dollars – NZD"},
		{"value": "Norway Kroner - NOK", "innertext": "Norway Kroner – NOK"},
		{"value": "Oman Rials - OMR", "innertext": "Oman Rials – OMR"},
		{"value": "Pakistan Rupees - PKR", "innertext": "Pakistan Rupees – PKR"},
		{"value": "Palladium Ounces - XPD", "innertext": "Palladium Ounces – XPD"},
		{"value": "Peru Nuevos Soles - PEN", "innertext": "Peru Nuevos Soles – PEN"},

		{"value": "Philippines Pesos - PHP", "innertext": "Philippines Pesos – PHP"},
		{"value": "Platinum Ounces - XPT", "innertext": "Platinum Ounces – XPT"},
		{"value": "Poland Zlotych - PLN", "innertext": "Poland Zlotych – PLN"},
		{"value": "Portugal Escudos - PTE", "innertext": "Portugal Escudos – PTE"},
		{"value": "Qatar Riyals - QAR", "innertext": "Qatar Riyals – QAR"},
		{"value": "Romania New Lei - RON", "innertext": "Romania New Lei – RON"},

		{"value": "Romania Lei - ROL", "innertext": "Romania Lei – ROL"},
		{"value": "Russia Rubles - RUB", "innertext": "Russia Rubles – RUB"},
		{"value": "Saudi Arabia Riyals - SAR", "innertext": "Saudi Arabia Riyals – SAR"},
		{"value": "Silver Ounces - XAG", "innertext": "Silver Ounces – XAG"},
		{"value": "Singapore Dollars - SGD", "innertext": "Singapore Dollars – SGD"},
		{"value": "Slovakia Koruny - SKK", "innertext": "Slovakia Koruny – SKK"},

		{"value": "Slovenia Tolars - SIT", "innertext": "Slovenia Tolars – SIT"},
		{"value": "South Africa Rand - ZAR", "innertext": "South Africa Rand – ZAR"},
		{"value": "South Korea Won - KRW", "innertext": "South Korea Won – KRW"},
		{"value": "Spain Pesetas - ESP", "innertext": "Spain Pesetas – ESP"},
		{"value": "Special Drawing Rights (IMF) - XDR", "innertext": "Special Drawing Rights (IMF) – XDR"},
		{"value": "Sri Lanka Rupees - LKR", "innertext": "Sri Lanka Rupees – LKR"},

		{"value": "Sudan Dinars - SDD", "innertext": "Sudan Dinars – SDD"},
		{"value": "Sweden Kronor - SEK", "innertext": "Sweden Kronor – SEK"},
		{"value": "Switzerland Francs - CHF", "innertext": "Switzerland Francs – CHF"},
		{"value": "Taiwan New Dollars - TWD", "innertext": "Taiwan New Dollars – TWD"},
		{"value": "Thailand Baht - THB", "innertext": "Thailand Baht – THB"},
		{"value": "Trinidad and Tobago Dollars - TTD", "innertext": "Trinidad and Tobago Dollars – TTD"},

		{"value": "Tunisia Dinars - TND", "innertext": "Tunisia Dinars – TND"},
		{"value": "Turkey New Lira - TRY", "innertext": "Turkey New Lira – TRY"},
		{"value": "United Arab Emirates Dirhams - AED", "innertext": "United Arab Emirates Dirhams – AED"},
		{"value": "United Kingdom Pounds - GBP", "innertext": "United Kingdom Pounds – GBP"},
		{"value": "United States Dollars - USD", "innertext": "United States Dollars – USD"},
		{"value": "Venezuela Bolivares - VEB", "innertext": "Venezuela Bolivares – VEB"},

		{"value": "Vietnam Dong - VND", "innertext": "Vietnam Dong – VND"},
		{"value": "Zambia Kwacha - ZMK", "innertext": "Zambia Kwacha – ZMK"}
];